name: Laravel

on:
  push:
    branches: [ master ]

jobs:
    code-check:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    tools: php-cs-fixer
            -   run: 'Coders tape/Advanced 6/composer' install --no-progress
            -   run: "Coders tape/Advanced 6/composer" check-cs
